[package]
name = "mg"
version = "0.1.0"
edition = "2021"
authors = ["Alwin Doss <alwindoss84@gmail.com>"]
description = "A simple minigrep tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
